import isAuthenticated from "../config/authentication.js";
import {createPost,dltPost,getAllPost,getFollowingPost,like} from "../controllers/postController.js";
import express from "express";
const router = express.Router();
router.route("/create").post(isAuthenticated, createPost);
router.route("/create").post(isAuthenticated,dltPost);
router.route("/delete/:id").delete(dltPost);
router.route("/like/:id").put(isAuthenticated,like);
router.route("/allPost/:id").get(isAuthenticated,getAllPost);
router.route("/followingPost/:id").get(isAuthenticated,getFollowingPost);
export default router;
